# .repo-sync.yaml - repo-sync configuration for ha-4noks-elios4you

template:
  owner: alexdelprete
  repo: ha-integration-template
  branch: main

vars:
  # -- Identity --
  repo_name: ha-4noks-elios4you
  integration_name: 4-noks Elios4you
  component_dir: 4noks_elios4you
  domain: 4noks_elios4you
  default_branch: main

  # -- 4noks workaround --
  needs_symlink: true
  python_import_name: fournoks_elios4you

  # -- HA/HACS --
  ha_min_version: "2024.12.0"
  hide_default_branch: false
  ignore_brands: false

  # -- Workflow tuning --
  jsonlint_flags: ""
  pymarkdown_config: "--config .pymarkdown.json"
  version_grep_pattern: "VERSION = "

  # -- Dependabot --
  dependabot_interval: weekly
  dependabot_time: ""
  dependabot_timezone: ""

  # ── Pyproject tools tuning ──
  include_mypy: false
  ruff_extend_exclude: ["build", "dist", "e4u-client"]
  ruff_lint_extra_ignores: ["ASYNC109", "ASYNC110", "N999", "PLW1641", "TC006", "UP046", "UP047", "UP049"]
  ruff_lint_extra_perfile_ignores:
    "custom_components/4noks_elios4you/api.py": ["S101", "TRY301"]
    "custom_components/4noks_elios4you/coordinator.py": ["DTZ005"]
  ruff_tests_extra_ignores: ["INP001", "E402"]
  pymarkdown_line_length: 180
  pymarkdown_strict_md013: true

  # -- Extras --
  requirements_extra_deps: ["telnetlib3>=2.0.4"]
  gitignore_extra: []
  bug_extra_fields: []
  config_extra_links: []

copy_files:
  - .gitattributes
  - .github/workflows/dbautomerge.yml
  - .github/FUNDING.yml
  - LICENSE

template_files:
  - .github/workflows/lint.yml
  - .github/workflows/test.yml
  - .github/workflows/validate.yml
  - .github/workflows/release.yml
  - .github/dependabot.yml
  - .github/ISSUE_TEMPLATE/bug.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/ISSUE_TEMPLATE/config.yml
  - .pre-commit-config.yaml
  - hacs.json
  - .gitignore
  - requirements-dev.txt
  - .devcontainer.json
  - docs/releases/README.md

marker_files:
  CLAUDE.md:
    - template: CLAUDE_SHARED.md.j2
      begin: "<!-- BEGIN SHARED:repo-sync -->"
      end: "<!-- END SHARED:repo-sync -->"
  README.md:
    - template: README_BADGES.md.j2
      begin: "<!-- BEGIN SHARED:repo-sync:badges -->"
      end: "<!-- END SHARED:repo-sync:badges -->"
    - template: README_INSTALLATION.md.j2
      begin: "<!-- BEGIN SHARED:repo-sync:installation -->"
      end: "<!-- END SHARED:repo-sync:installation -->"
    - template: README_CONTRIBUTING.md.j2
      begin: "<!-- BEGIN SHARED:repo-sync:contributing -->"
      end: "<!-- END SHARED:repo-sync:contributing -->"
    - template: README_LICENSE.md.j2
      begin: "<!-- BEGIN SHARED:repo-sync:license -->"
      end: "<!-- END SHARED:repo-sync:license -->"
  pyproject.toml:
    - template: PYPROJECT_TOOLS.toml.j2
      begin: "# <!-- BEGIN SHARED:repo-sync -->"
      end: "# <!-- END SHARED:repo-sync -->"
